Add files via upload

diff --git a/ngx b/ngx
--- a/ngx
+++ b/ngx
@@ -2,30 +2,28 @@
 #
 #configurar proxy
 
+#SCRIPTS=~/scripts
+
+NEW_CONF=$1
+OLD_CONF=$2
+ 
 #configurando nginx
 echo "$(tput bold)Configurando nginx$(tput sgr0)"
 
-cp ~/scripts/tomcat-proxy.conf /etc/nginx/sites-available/tomcat-proxy.conf && \
-rm /etc/nginx/sites-enabled/default && \
-ln -s /etc/nginx/sites-available/tomcat-proxy.conf /etc/nginx/sites-enabled/tomcat-proxy.conf 
+if [ -z $NEW_CONF ]; then
+	nginx -t && nginx -s reload
+	else
+#cp ~/scripts/tomcat-proxy.conf /etc/nginx/sites-available/tomcat-proxy.conf && \
+#rm /etc/nginx/sites-enabled/default && \
+#ln -s /etc/nginx/sites-available/tomcat-proxy.conf /etc/nginx/sites-enabled/tomcat-proxy.conf 
+
+cp $SCRIPTS/$NEW_CONF /etc/nginx/sites-available && \
+rm /etc/nginx/sites-enabled/$OLD_CONF && \
+ln -s /etc/nginx/sites-available/$NEW_CONF /etc/nginx/sites-enabled
 
 (nginx -t && nginx -s reload && \
-echo 'nginx configurado' || echo 'error al configurar nginx') >> $PS_LOG/enketo-install
-
-#configurando tomcat
-echo "$(tput bold)Configurando tomcat$(tput sgr0)"
-
-(sed -i.orig '/\/Engine/ i \ \
-	<!-- Redireccionar proxy --> \
-	<Valve className="org.apache.catalina.valves.RemoteIpValve" \
-		internalProxies="127\\.0\\.[0-1]\\.1" \
-		remoteIpHeader="x-forwarded-for" \
-		requestAttributesEnabled="true" \
-		protocolHeader="x-forwarded-proto" \
-		protocolHeaderHttpsValue="https"/>' /etc/tomcat8/server.xml && \
-echo "Se ha actualizado el archivo /etc/tomcat8/server.xml" || \
-echo 'ha ocurrido un error') >> $PS_LOG/enketo-install
-
+echo "$NEW_CONF : configuración exitosa" || echo "error al configurar $NEW_CONF") >> $PS_LOG/proxy-install
+fi
 exit
 
 
